/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Login$Params as Login$Params } from './fn/auth/login';
export { login as login } from './fn/auth/login';
export type { Refresh$Params as Refresh$Params } from './fn/auth/refresh';
export { refresh as refresh } from './fn/auth/refresh';
export type { GameGetall$Params as GameGetall$Params } from './fn/game/game-getall';
export { gameGetall as gameGetall } from './fn/game/game-getall';
export type { GameResult$Params as GameResult$Params } from './fn/game/game-result';
export { gameResult as gameResult } from './fn/game/game-result';
export type { GameCompletedToday$Params as GameCompletedToday$Params } from './fn/game/game-completed-today';
export { gameCompletedToday as gameCompletedToday } from './fn/game/game-completed-today';
export type { WordleToday$Params as WordleToday$Params } from './fn/wordle/wordle-today';
export { wordleToday as wordleToday } from './fn/wordle/wordle-today';
export type { PalyerAutocomplete$Params as PalyerAutocomplete$Params } from './fn/player/palyer-autocomplete';
export { palyerAutocomplete as palyerAutocomplete } from './fn/player/palyer-autocomplete';
