/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Login$Params as Login$Params } from './fn/auth/login';
export { login as login } from './fn/auth/login';
export type { Refresh$Params as Refresh$Params } from './fn/auth/refresh';
export { refresh as refresh } from './fn/auth/refresh';
export type { GameGetall$Params as GameGetall$Params } from './fn/game/game-getall';
export { gameGetall as gameGetall } from './fn/game/game-getall';
